<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>AdoWorkItemTreeCloner</AssemblyName>
    <RootNamespace>AdoWorkItemTreeCloner</RootNamespace>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);SA0001</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Spectre.Console" />
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../AdoWorkItemTreeCloner.Core/AdoWorkItemTreeCloner.Core.csproj" />
  </ItemGroup>
</Project>
